### ISSUE TITLE
[Suggestion] Integrated Dynamics

### ISSUE THREAD

**Issue by vertex101** [MelanX/CaveStone#3]
i see you are using Simple Storage Network for like an AE type thing but i wanted to suggest Integrated Dynamics as its still simple n adds in little extra things that Simple Storage Network doesnt have

**Comment by MelanX** [comment]
I totally understand why this is a request, and can confirm that it's a mod which can more things than Simple Storage Network. However, this mod is *too* powerful for this modpack. It can be used for so much more than just the storage thing (if it even can do this, I didn't play a lot with it). Thank you for the request, but this mod is too powerful for this kind of modpack.
